title: Miguel Angel Ballen
description: > # this means to ignore newlines until "baseurl:"
    Hi! You're very welcome to my profile page! Github pages is the
    perfect place to post interesting content and generate cool pages like this
    with automatic content generator (Jekyll).

baseurl: "/monday" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: Miguel Angel Ballén
tagline: Systems and computing engineering student, software developer and musician!
about-description: My name is Miguel, and I'm currently finishing my system and
 computing engineering career at National University Of Colombia, started in
 2012. I'm very proud to show you some of my relevant academic projects and
 some interesting info about music and things that I love!
pic: mig.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: migaballengal@unal.edu.co # Add your Email address
phone: 300 237 19 39 # Add your Phone number
website: mballeng91.github.io # Add your website, do not add http://
linkedin: mballeng91 # Add your Linkedin handle
github: mballeng91 # Add your Github handle
twitter: '@mballeng91' # Add your Twitter handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]

theme: jekyll-theme-midnight